spring.application.name=muckzi-back

# =========================================================
# 1. Oracle Database ?? ?? (?? ??? ??? ??)
# =========================================================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# localhost:1521 ??? xe(?? ?? ??? ????)? ?????.
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# ?? ??? SQL Developer ??? ? ? ??? ?? ID? ????? ?????!
spring.datasource.username=system
spring.datasource.password=1234

# =========================================================
# 2. JPA / Hibernate ?? (?????? ?? ??)
# =========================================================
# ?? ???? SQL? ?? ??????, ???? ??? ??? ??? ??? validate? ?????.
spring.jpa.hibernate.ddl-auto=validate
# ???? ???? ??? SQL ???? ??? ????? ????? (????).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# 3. Swagger (Springdoc) ??
# =========================================================
# ????? ??? ??? ??? ??
springdoc.packages-to-scan=com.muckzi
# Swagger UI ?? ?? ?? (/swagger-ui.html? ?? ? ?? ??)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

# =========================================================
# 4. JWT ??
# =========================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000